"use client"
import type { Metadata } from "next";
import { BellIcon,MessageCircleCodeIcon,SearchIcon} from "lucide-react";
import { ConvexReactClient } from "convex/react";
import { ConvexClientProvider } from "./ConvexClientProvider";
import { ClerkProvider,SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton, } from '@clerk/nextjs'
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


const convex = new ConvexReactClient(process.env.NEXT_PUBLIC_CONVEX_URL!);

 const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            <header className="flex justify-between items-center text-black bg-white p-10 gap-7 h-16">
              <h1 className="font-bold text-2xl">Chatify</h1>
              {/* Show the sign-in and sign-up buttons when the user is signed out */}
              <div className="flex space-x-9">
              
             
              <div className="flex flex-row  justify-center  items-center space-x-7">
              <BellIcon/>
              <MessageCircleCodeIcon/>
              </div>
              <SignedOut>
                <SignInButton />
                <SignUpButton>
                  <button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
                    Sign Up
                  </button>
                </SignUpButton>
              </SignedOut>
              {/* Show the user button when the user is signed in */}
              <SignedIn>
                <UserButton />
              </SignedIn>
              </div>
            </header>
            <ConvexClientProvider>
        {children}
      </ConvexClientProvider>
          </body>
        </html>
    </ClerkProvider>
  )
}


// https://github.com/ultimate-knight/Messenger-app.git